pipeline:
  backend:
    image: node
    commands:
      - npm install
      - npm test
services:
  database:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root